#!/bin/bash
# Generated by OneBTCPlace.com
temp=$(ps aux | grep 666Coind | grep -v grep)
echo $temp
#if [[ "$temp" == * 666Coind * ]]
if echo "$temp" | grep -q "666Coind"; then
"echo 666Coind  Already Running!"
else
nice -n 15 666Coind
fi
